import os
import re

# 设置你要扫描的文件夹
target_folders = ["src", "backend"] 
# 设置你要忽略的文件夹
ignore_dirs = ["node_modules", "__pycache__", ".git", "venv", "dist", "build", ".idea", ".vscode"]
# 设置你要读取的文件后缀
valid_extensions = [".jsx", ".js", ".py", ".css", ".html", ".json"]

output_file = "all_code.txt"

# 项目概况总结
PROJECT_SUMMARY = """
================================================================================
项目概览 (Project Summary) - Generated by Trae
================================================================================
1. 项目名称：听见·鼓浪屿 (Gulangyu.AI) —— 多感知无障碍导航系统

2. 核心框架：
   - 前端：React 19 + Vite 7 + Tailwind CSS 3
   - 后端：Python 3.12 + FastAPI + SQLite

3. 关键技术栈：
   - UI/UX设计：Lucide React (图标), Glassmorphism (高级毛玻璃), Apple-style CSS Animations
   - 数据可视化：Recharts (用于构建策展人看板、热力图、交互趋势分析)
   - AI与多模态：
     - LLM: 接入阿里云通义千问 (Qwen-Turbo 用于对话, Qwen-VL-Max 用于视觉识别)
     - 语音交互: Web Speech API (STT/TTS) + 浏览器语音合成
   - 硬件能力：HTML5-QRCode (扫码), Navigator Vibration API (触感反馈)

4. 主要功能模块：
   - 沉浸式首页 (App.jsx)：
     - 实现 Apple 官网级 "中心扩散" 动效与纯 CSS 构建的 iPhone 16 Pro (灵动岛) Mockup。
     - 包含项目背景、算法验证(Lightbox)、交互分析、策展人看板等模块化组件。
   - AI 语音导览 (AiPage.jsx)：
     - 专为视障设计的语音交互界面，已修复 "滚动穿透 (Scroll Bleeding)" 问题。
     - 支持实时语音识别与流式播报。
   - 后端服务 (backend/main.py)：
     - 提供 RESTful API (建筑数据 CRUD、AI Chat、Vision Analysis、路径规划)。
     - 集成 SQLite 数据库与静态资源服务。
   - 策展人模式：
     - Web 端：全屏数据可视化大屏 (Dashboard)。
     - 移动端：内嵌于 Mockup 的内容管理系统 (需管理员密码)。

5. 当前开发阶段：
   - 状态：v2.0 Beta (高保真原型 / High-Fidelity Prototype)
   - 最近里程碑：
     - 完成首页视觉重构 (Dark Mode Glassmorphism + iPhone 16 Pro Frame)。
     - 修复内嵌 App 的滚动交互问题。
     - 实现策展人数据看板的多端适配。

6. 敏感信息过滤说明：
   - 本文件已自动过滤代码中的 API Key (sk-***) 和其他敏感配置。
================================================================================
"""

def merge_files():
    with open(output_file, "w", encoding="utf-8") as outfile:
        # 1. 写入项目总结
        outfile.write(PROJECT_SUMMARY)
        outfile.write("\n\n")

        # 2. 遍历并写入代码文件
        for root, dirs, files in os.walk("."):
            # 过滤掉不需要的文件夹
            dirs[:] = [d for d in dirs if d not in ignore_dirs]
            
            for file in files:
                # 只处理指定后缀的文件
                if any(file.endswith(ext) for ext in valid_extensions):
                    # 排除掉脚本自己和输出文件
                    if file == "merge_code.py" or file == output_file:
                        continue
                    
                    # 排除 package-lock.json (太长且通常不需要)
                    if file == "package-lock.json":
                        continue
                        
                    file_path = os.path.join(root, file)
                    
                    # 写入分隔符和文件名
                    outfile.write(f"\n{'='*50}\n")
                    outfile.write(f"FILE: {file_path}\n")
                    outfile.write(f"{'='*50}\n\n")
                    
                    try:
                        with open(file_path, "r", encoding="utf-8") as infile:
                            content = infile.read()
                            
                            # --- 敏感信息过滤 ---
                            # 1. 过滤常见的 API Key 格式 (sk-...)
                            content = re.sub(r'(sk-)[a-zA-Z0-9]{20,}', r'\1********************', content)
                            # 2. 过滤管理员密码
                            content = content.replace('"8888"', '"****"') 
                            
                            outfile.write(content)
                    except Exception as e:
                        outfile.write(f"Error reading file: {e}")
                    
                    outfile.write("\n")

    print(f"✅ 完成！项目概览与所有代码已合并到 {output_file}")

if __name__ == "__main__":
    merge_files()
